apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      nodeSelector:
        role: backend
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["sh", "-c", "bunx prisma migrate deploy --schema=/app/prisma/schema.prisma"]
          envFrom:
            - secretRef:
                name: annon-review-secret
      restartPolicy: Never