apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure  # Automatically retries
      nodeSelector:
        role: backend
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["sh", "-c", "pg_isready -h postgres-service -p 5432 -U user_anon && bunx prisma migrate deploy --schema=/app/prisma/schema.prisma"]
          envFrom:
            - secretRef:
                name: annon-review-secret
          env:
            - name: PGCONNECT_TIMEOUT
              value: "30"
