apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-replica-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pgbouncer-replica
  ports:
    - port: 6432
      targetPort: 6432